Ticket 23 configure bluesky logging
ISISComputingGroup/system_tests pull request #114
Opened 2024-10-17 10:47 UTC by Chsudeepta

### Description of work

Some system tests have been added for testing the bluesky logger

### Ticket

[*Link to Ticket*](https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/23)

### Acceptance criteria

The system tests should run successfully as a complete set or when executed individually

### System tests

Added tests to check the following: 
1. Log folder is created when logging is requested
2. Log file is created when logging is requested
3. The log message is present in the log file.

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

2024-10-24 16:05 UTC, jackbdoughty requested changes
After these changes, running this test module in one go I get test failures on lines `224` and `212` of `assert os.path.exists(qualified_log_filename) == True` `AssertionError`. I defined `LOG_FILE_NAME = "bluesky.log"`

2024-10-25 09:32 UTC, Chsudeepta commented on test_bluesky.py
> +    def test_GIVEN_logging_is_requested_THEN_the_log_folder_exists():
Done.

2024-10-25 09:32 UTC, Chsudeepta commented on test_bluesky.py
> +        qualified_log_filename = os.path.join(log_path, LOG_FILE_NAME)
Added missed constant

2024-10-25 09:36 UTC, Chsudeepta commented
@jackbdoughty , I have corrected the issues, including the ruff ones

2024-10-28 10:09 UTC, jackbdoughty approved these changes

2024-10-28 12:12 UTC, merged